project_id = "gadgexo"

[db]
port = 54322
major_version = 15

[db.seed]
enabled = true
sql_paths = ["seed/seed.sql"]

[api]
enabled = true
port = 54321

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://gadgexo.vercel.app"
